### ISSUE TITLE
python등 프로그래밍 언어 컨텐츠를 위한 새로운 directory 추가 제안

### ISSUE THREAD

**Issue by al-bur** [klassicode0/ComputerScience#4]
@rootkwak528 @klassicode0 @gyoforit 

현재 `python is와 ==` 글이 `software-engineering` 디렉토리에 위치해있습니다.

앞으로 python, java, javascript등 여러 프로그래밍 언어에 관한 질문들이 올라올 것을 생각해 최상단에 
`programming_language` 디렉토리를 추가하는 것은 어떨까요??

**Comment by gyoforit** [comment]
좋아요!

**Comment by rootkwak528** [comment]
좋은 생각이예요!
수정해서 커밋해주실래요?

**Comment by al-bur** [comment]
폴더구조 변경 완료했습니다!
