### ISSUE TITLE
13주차 마지막 웹팩 문제 분류 이동 제안 (프로그래밍 => 웹)

### ISSUE THREAD

**Issue by rootkwak528** [klassicode0/ComputerScience#5]
웹팩은 프로그래밍 전반에서 사용하기 보다 웹 프론트엔드 관련 모듈러로 알고 있습니다.
문제 분류를 기존의 "프로그래밍"에서 "웹"으로 옮겨서 주제의 특수성을 좀더 세분화하는 것이 어떨까요?

**Comment by gyoforit** [comment]
좋아요!!
